### ISSUE TITLE
deep copy functions (just-clone, just-extend) loses class reference when a class instatiation is passed

### ISSUE THREAD

**Issue by anthonyma94** [angus-c/just#509] opened 2022-11-14 15:24 UTC
When a non-POJO object is passed to be cloned, the object is converted into a POJO, losing all functions.

```ts
class Test {
  test() {
    console.log("testing");
  }
}

const test = new Test();
test.test() // prints "testing";

const cloned = clone(test);
cloned.test() // TypeError: test.test is not a function

const deepExtended = extend(true, {}, {test: test}); // Only fails when the object is passed as the second object
deepExtended.test.test() // TypeError: deepExtended.test.test is not a function
```

**Comment by angus-c** [comment] 2022-11-19 21:46
Duplicate of #506

**Closed by angus-c** 2022-11-19 21:46 UTC
