### ISSUE TITLE
Reconsider TypeScript

### ISSUE THREAD

**Issue by jedmao** [angus-c/just#126] opened 2019-03-07 23:53 UTC
TypeScript type definitions were already requested in #20 and #66 back in 2016-2017, but the landscape has changed much since then.

[Two concerns were expressed in #20](https://github.com/angus-c/just/issues/66#issuecomment-337088355), that you would like to avoid, which I will address below, but first let me state the value proposition.

## Value Proposition

For a library such as this, it makes all the sense in the world for the source to be written in TypeScript for the following reasons:
1. The type definition files (`*.d.ts`) can be generated at compile time for free. Nobody has to manually update these files, leading to version out-of-sync issues.
1. Types remain in sync with each version that is published. You just can't get this feature without TS source code.
1. You don't have to install two packages for each "just" package (e.g., `npm install --save just-omit && npm install --save-dev @types/just-omit`).
1. Users who don't use TypeScript can still benefit via [Automatic Type Acquisition](https://code.visualstudio.com/Docs/languages/javascript#_intellisense-is-not-working-for-external-libraries).

## Transpilation step

There's obviously no getting around this one if TS were to be used, but I'd like to know, specifically, what the concerns around the transpilation step are.

## Size increase

This one is probably a misconception, an outdated fear or an exaggeration. As a superset of JavaScript, TypeScript seeks not to add any language constructs of their own. As long as we steer away from inheritance and down-level compilation, there's really nothing to fear here. All the type information and interfaces disappear at compile time.

Let's take [`just-omit`](https://github.com/angus-c/just/blob/master/packages/object-omit/index.js) as an example. Currently, if I remove the comments, the file size is **193 bytes min / 177 bytes min + gzip**.

If I were to convert it into TypeScript, it would look something like this:

```ts
export = omit

/**
 * The opposite of `just-pick`; this method creates an object composed of the
 * own and inherited enumerable properties of `object` that are not omitted.
 * 
 * @category Object
 * @returns A new object with specified keys omitted from the source `object`.
 * @example ...
 */
function omit<T extends object, K extends keyof T>(
  /**
   * The source object.
   */
  object: T | null | undefined,
  /**
   * The property names to omit.
   */
  ...paths: Array<K | ReadonlyArray<K>>
) {
  const result = {} as Pick<T, Exclude<keyof T, K>>;
  for (const prop in object) {
    if (!object.hasOwnProperty || object.hasOwnProperty(prop)) {
      if (paths.indexOf(prop as unknown as K) === -1) {
        result[prop as string] = object[prop];
      }
    }
  }
  return result
}
```

Which compiles to **214 bytes min / 190 bytes min + gzip**:
```js
"use strict";
function omit(object) {
    var paths = [];
    for (var _i = 1; _i < arguments.length; _i++) {
        paths[_i - 1] = arguments[_i];
    }
    var result = {};
    for (var prop in object) {
        if (!object.hasOwnProperty || object.hasOwnProperty(prop)) {
            if (paths.indexOf(prop) === -1) {
                result[prop] = object[prop];
            }
        }
    }
    return result;
}
module.exports = omit;
```
The delta is only **21 bytes and 13 bytes**, respectively, and I could have avoided that if I stuck to the current `just-omit` implementation and didn't use the spread (`...`) operator for `paths`.

Point is, it's basically the same, but you gain so much value in serving the community with the type information they need. Even if they aren't using TypeScript, editors like vscode can still pull-in type information via [type acquisition](https://code.visualstudio.com/Docs/languages/javascript#_intellisense-is-not-working-for-external-libraries), so everybody wins.

> `Automatic Type Acquisition` works for dependencies downloaded by npm (specified in `package.json`), Bower (specified in `bower.json`), and for many of the most common libraries listed in your folder structure (for example `jquery-3.1.1.min.js`).

## Conclusion

As long as you're open to the idea, I think the community can start to submit PRs incrementally. There's no reason everything has to be done all at once.

**Comment by angus-c** [comment] 2019-03-08 05:14
Hi Jed, thanks for the issue and I appreciate you taking the time to make it thorough and well-reasoned.

I agree that TS usage is growing and I'm pretty sure there are a section of developers who would be more likely to use Just if it had a typed interface. However I'm still not sure it's necessary to write Just in TS in order to use it in JS. As you can probably guess I'm pretty obsessive about perf and size impacts of every line of code in Just, so I'd want to check each PR carefully and see how it compiles to JS, which is a lot of work. Also while I take your point that transpiling will only marginally increase the shipped size, it will also require source map generation. The bare bones simplicity of the current set up has made the development / debug experience a joy and I'm wary about losing that.

There are already 3 Just module definitions in [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped) and I'd more than welcome additions to that repo. I know that doesn't address your points 2 and 3 above but I do think it would open up Just to TS users.

**Comment by jedmao** [comment] 2019-03-08 06:03
@angus-c I love your response, even though I have a different mindset. I can tell that you read the whole post and carefully responded to every point I made. Respect! 🙇 

I don't have any more ammo to bring to this conversation, so it looks like I'll have to fork it myself if I want to take it in this direction. I'm going to close the issue, but thanks for listening!

**Comment by jedmao** [comment] 2019-03-08 07:17
I just wanted to give you a taste for what an actual PR might look like. See https://github.com/angus-c/just/commit/a093c6debfb0e9778fb55bbbb68f342c7e7ba5ff

**Comment by angus-c** [comment] 2019-03-08 17:15
But then I have to transpile this because of `...rest`. I'm actually trying to use almost exclusively ES3 (`Object(keys)`  is an exception) for perf reasons.

**Comment by jedmao** [comment] 2019-08-23 18:53
FWIW, I created [a separate project, Queso](http://queso.surge.sh/) that is in a similar spirit as Just, but 1st-class TS support.

**Comment by ilearnio** [comment] 2021-03-12 01:10
I agree that there's no need to rewrite just in TypeScript. But adding TypeScript definition files into every just package makes a lot of sense. Since right now I'm unable to use just in my TS project as it lacks these definitions, and TS strict mode doesn't allow me to use packages without definitions

**Comment by angus-c** [comment] 2021-03-15 01:38
@ilearnio yeah I'm leaning towards that solution. Happy to accept PRs if you want to start the ball rolling btw :)

BTW there are also some TS definitions for Just modules in [Definitely Typed](https://github.com/DefinitelyTyped/DefinitelyTyped).

**Comment by angus-c** [comment] 2021-04-04 01:19
@ilearnio can I validate my .js file against a TypeScript definition file? It seems like I should be able to use `tsc my.js --checkJS`, but apparently this only works if the file includes jsdocs, which seems surprising given that a TS definition file can be generated from jsdocs.

**Comment by ilearnio** [comment] 2021-04-04 08:43
@angus-c There seems to be no built in way in TypeScript itself to test typings for pure JS projects, see https://github.com/microsoft/TypeScript/issues/7661.
However there is this testing tool that perhaps may help https://github.com/ai/check-dts.

Alternatively, I would go with simply adding some `types.test.ts` files that would look like so:

```
import pick from 'just-pick'

// Incorrect usage

// @ts-expect-error
pick([])
// @ts-expect-error
pick()
// @ts-expect-error
pick({ foo: 'bar' }, 123)

// Correct usage

pick({ foo: 'bar' }, ['foo'])
```

So whenever such files compiled with `tsc` the should not produce any TS errors (except for those that are catched with `@ts-expect-error`)

**Comment by angus-c** [comment] 2021-04-04 23:02
First 14 definitions added

**Comment by jimmywarting** [comment] 2021-05-17 17:15
I advocate jsDoc instead of TypeScript.

- You can get same level typing support (even without jsdoc - depending on how you write your code - default arguments / class properties helps)
- Don't have to transpile anything
- run much faster
- Fewer dependencies
- Less configuration
- Can be imported from browser
- Don't need any build process
- No need for SourceMap 
- TypeScript is not standard
  - uses public/private instead of `#`
- Can't simply copy paste anything and have it run instantly in the browser or onto some other JS only project.
- Always stays in the shadow of javascript - will always be one step behind new features
  - can't use private class methods for example `#foo() { ... }`
  - just tried to use `addEventListener(evt, fn, { signal })` and it complains about signal cuz it's not up to speed.
- there is nothing wrong with a loosed typed language
  - TypeScript is really bad at this. You are allowed to do many loose hacks that TS have hard time to graps. It's perfectly fine to add 1000 to a Date object and get a number back. Or add one to many argument to a function that only accepts 3, Blob parts are not restricted to only string, typed arrays and blob, it accepts anything, cuz the default behavior is to cast any unknown object into a string, same thing with Response, Request, FormData, URLSearchParams unknown arguments gets casted to a string but TS complains about this. It throws if you try to do `fetch(new URL(str))`

I love typing and i support it too (with jsdoc+followJs) but i hate the syntax cuz it's not vanilla javascript - all of you who comes from java, or .NET or any other typed language and don't want to learn vanilla javascript, stick with what you know and transpile it to web assembly instead. I also love our beloved loosed typed language - it's not a bug, it's a feature!

> @angus-c There seems to be no built in way in TypeScript itself to test typings for pure JS projects, see 

how about this?
```js
// @ts-check
```

**Comment by angus-c** [comment] 2021-05-28 19:47
@jimmywarting I share many of your concerns about using Typescript syntax directly, but note they don't really apply here. There is no TypeScript in Just source code, just type definition files for consuming app to validate against.

**Comment by angus-c** [comment] 2021-08-30 19:36
Closing as we now have a [documented strategy](https://github.com/angus-c/just#typescript-) for this.

**Closed by angus-c** 2021-08-30 19:36 UTC
