### ISSUE TITLE
just-safe-get does not support arrays within objects as lodash does

### ISSUE THREAD

**Issue by charleskoehl** [angus-c/just#82] opened 2017-11-27 20:00 UTC
Example:
```
const get = require('just-safe-get');

const obj = {a: {aa: [5,6,8]}, b: 4};

get(obj, 'a.aa[6]');

// undefined, but works in lodash/get
```

**Comment by angus-c** [comment] 2017-11-28 20:40
Hi Charles, I think you meant `get(obj, 'a.aa[1]');`.

As mentioned in the [TRADEOFFS.md](https://github.com/angus-c/just/blob/master/TRADEOFFS.md), _just-get_ follows the standard set by the popular [Dotty library](https://github.com/deoxxa/dotty) which supports the following syntax:

`get(obj, 'a.aa.1');`

**Comment by angus-c** [comment] 2017-12-01 22:40
Closing as this is by design and the functionality is available via an alternative syntax.

**Closed by angus-c** 2017-12-01 22:40 UTC
