### ISSUE TITLE
404 produced in documentation site

### ISSUE THREAD

**Issue by danawoodman** [angus-c/just#278] opened 2021-06-19 16:16 UTC
I'm noticing 404s when the initial render of the doc site occurs, for example, this page returns 404 initially: https://anguscroll.com/just/just-is-empty

I assume this may have something to do with Github Pages and the specific static site generator being used?

This is happening in Brave/Chrome/Safari.

![Image 2021-06-19 at 9 12 47 AM](https://user-images.githubusercontent.com/157695/122648524-85bceb80-d0de-11eb-8f2c-b2b0b3569ffb.jpg)

![Image 2021-06-19 at 9 16 09 AM](https://user-images.githubusercontent.com/157695/122648652-febc4300-d0de-11eb-8c3e-3a5d51183786.jpg)

![Image 2021-06-19 at 9 16 18 AM](https://user-images.githubusercontent.com/157695/122648659-0380f700-d0df-11eb-8977-a703b0c86923.jpg)

**Comment by angus-c** [comment] 2021-06-19 18:59
Hi @danawoodman, thanks for reporting.

The 404 is by design. It's a bit of a hack but [404.html ](https://github.com/angus-c/just/blob/gh-pages/404.html)should replicate the home page, then the javascript [reads the current page from the URL and the sets state to that function](https://github.com/angus-c/just/blob/gh-pages/javascripts/components/App.js#L24)

Not sure why it shows a 404 for you. What do you see if you put `https://anguscroll.com/just/404.html` in the address bar?

**Comment by angus-c** [comment] 2021-06-24 01:45
I just realized, it looks like you are seeing the intended content (I was confused buy the "sorry that page is missing" banner, which I don't see in my browser)

I should probably replace the 404 -> update state hack with something more robust.

**Comment by angus-c** [comment] 2021-08-30 20:22
Closing as a) intended content still shows b) update is non trivial (requires a router library and even then not sure how they will redirect 404s) and I'm just not going to have the time to improve it.

**Closed by angus-c** 2021-08-30 20:22 UTC
